schema_version = "1.0.0"
id = "optiloops"
name = "Optiloops"
version = "1.4.0"
tagline = "Optimize meshes by removing loops with angle threshold"
maintainer = "Vilem Duha, BlenderKit <admin@blenderkit.com>"
type = "add-on"
tags = ["Mesh", "Add Mesh"]
blender_version_min = "4.2.0"
license = ["GPL-2.0-or-later"]
website = "https://github.com/BlenderKit/Optiloops"
copyright = [
    "2023 Vilem Duha",
]